import React from 'react';
import styled from 'styled-components'

const Main = styled.main`
  flex: 1 1 auto;
`;

const Title = styled.h1`
  text-align: center;
`;

const Content = styled.p`
  padding: 20px;
`;

const Body = () => {

  return (
    <Main>
      <Title>Some title</Title>
      <Content>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquid, architecto autem cupiditate dolorem doloremque dolorum earum et expedita facilis impedit, inventore iure libero minus nam nisi nobis odio quae quod voluptatem. Accusamus adipisci aspernatur assumenda aut consequatur dolore enim error eum ex id impedit ipsam laborum magnam molestias nam nemo provident, quas quasi qui quo reiciendis unde vero voluptate. Adipisci eveniet nulla repudiandae vero. Aliquam debitis hic iusto labore laudantium magnam officia quas quos totam vitae. Accusantium aliquam aliquid amet blanditiis consectetur dignissimos dolorem doloribus id impedit inventore iusto laudantium maiores nam nemo nihil nisi optio, provident quo quod ratione sit sunt suscipit tempore temporibus tenetur voluptate voluptates voluptatum. Aliquam asperiores autem cupiditate delectus deleniti dignissimos earum excepturi expedita fuga fugit illo illum inventore ipsam iure laborum minus molestiae molestias mollitia nam obcaecati praesentium provident quis, quod reiciendis sed suscipit voluptas voluptate? Amet consectetur culpa delectus ducimus eaque eligendi fugiat ipsum perspiciatis quibusdam. Aut beatae dignissimos ea earum enim est et, inventore ipsa laborum numquam porro recusandae reiciendis, similique ullam vitae. Adipisci earum eligendi eos mollitia nam optio placeat quisquam quod. Adipisci asperiores debitis ea et eveniet ex, fugit hic iure neque pariatur perferendis quasi quibusdam sit tenetur ut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquid, architecto autem cupiditate dolorem doloremque dolorum earum et expedita facilis impedit, inventore iure libero minus nam nisi nobis odio quae quod voluptatem. Accusamus adipisci aspernatur assumenda aut consequatur dolore enim error eum ex id impedit ipsam laborum magnam molestias nam nemo provident, quas quasi qui quo reiciendis unde vero voluptate. Adipisci eveniet nulla repudiandae vero. Aliquam debitis hic iusto labore laudantium magnam officia quas quos totam vitae. Accusantium aliquam aliquid amet blanditiis consectetur dignissimos dolorem doloribus id impedit inventore iusto laudantium maiores nam nemo nihil nisi optio, provident quo quod ratione sit sunt suscipit tempore temporibus tenetur voluptate voluptates voluptatum. Aliquam asperiores autem cupiditate delectus deleniti dignissimos earum excepturi expedita fuga fugit illo illum inventore ipsam iure laborum minus molestiae molestias mollitia nam obcaecati praesentium provident quis, quod reiciendis sed suscipit voluptas voluptate? Amet consectetur culpa delectus ducimus eaque eligendi fugiat ipsum perspiciatis quibusdam. Aut beatae dignissimos ea earum enim est et, inventore ipsa laborum numquam porro recusandae reiciendis, similique ullam vitae. Adipisci earum eligendi eos mollitia nam optio placeat quisquam quod. Adipisci asperiores debitis ea et eveniet ex, fugit hic iure neque pariatur perferendis quasi quibusdam sit tenetur ut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquid, architecto autem cupiditate dolorem doloremque dolorum earum et expedita facilis impedit, inventore iure libero minus nam nisi nobis odio quae quod voluptatem. Accusamus adipisci aspernatur assumenda aut consequatur dolore enim error eum ex id impedit ipsam laborum magnam molestias nam nemo provident, quas quasi qui quo reiciendis unde vero voluptate. Adipisci eveniet nulla repudiandae vero. Aliquam debitis hic iusto labore laudantium magnam officia quas quos totam vitae. Accusantium aliquam aliquid amet blanditiis consectetur dignissimos dolorem doloribus id impedit inventore iusto laudantium maiores nam nemo nihil nisi optio, provident quo quod ratione sit sunt suscipit tempore temporibus tenetur voluptate voluptates voluptatum. Aliquam asperiores autem cupiditate delectus deleniti dignissimos earum excepturi expedita fuga fugit illo illum inventore ipsam iure laborum minus molestiae molestias mollitia nam obcaecati praesentium provident quis, quod reiciendis sed suscipit voluptas voluptate? Amet consectetur culpa delectus ducimus eaque eligendi fugiat ipsum perspiciatis quibusdam. Aut beatae dignissimos ea earum enim est et, inventore ipsa laborum numquam porro recusandae reiciendis, similique ullam vitae. Adipisci earum eligendi eos mollitia nam optio placeat quisquam quod. Adipisci asperiores debitis ea et eveniet ex, fugit hic iure neque pariatur perferendis quasi quibusdam sit tenetur ut?
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias aliquid, architecto autem cupiditate dolorem doloremque dolorum earum et expedita facilis impedit, inventore iure libero minus nam nisi nobis odio quae quod voluptatem. Accusamus adipisci aspernatur assumenda aut consequatur dolore enim error eum ex id impedit ipsam laborum magnam molestias nam nemo provident, quas quasi qui quo reiciendis unde vero voluptate. Adipisci eveniet nulla repudiandae vero. Aliquam debitis hic iusto labore laudantium magnam officia quas quos totam vitae. Accusantium aliquam aliquid amet blanditiis consectetur dignissimos dolorem doloribus id impedit inventore iusto laudantium maiores nam nemo nihil nisi optio, provident quo quod ratione sit sunt suscipit tempore temporibus tenetur voluptate voluptates voluptatum. Aliquam asperiores autem cupiditate delectus deleniti dignissimos earum excepturi expedita fuga fugit illo illum inventore ipsam iure laborum minus molestiae molestias mollitia nam obcaecati praesentium provident quis, quod reiciendis sed suscipit voluptas voluptate? Amet consectetur culpa delectus ducimus eaque eligendi fugiat ipsum perspiciatis quibusdam. Aut beatae dignissimos ea earum enim est et, inventore ipsa laborum numquam porro recusandae reiciendis, similique ullam vitae. Adipisci earum eligendi eos mollitia nam optio placeat quisquam quod. Adipisci asperiores debitis ea et eveniet ex, fugit hic iure neque pariatur perferendis quasi quibusdam sit tenetur ut?
      </Content>
    </Main>
  );
};

export default Body;
